// Code generated by "stringer -linecomment -type=FormatType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FormatInvalid-0]
	_ = x[FormatName-1]
	_ = x[FormatVersion-2]
	_ = x[FormatCurve-3]
	_ = x[FormatGroups-4]
	_ = x[FormatNotAfter-5]
	_ = x[FormatFingerprint-6]
}

const _FormatType_name = "FormatInvalidnameversioncurvegroupsnotAfterfingerprint"

var _FormatType_index = [...]uint8{0, 13, 17, 24, 29, 35, 43, 54}

func (i FormatType) String() string {
	if i < 0 || i >= FormatType(len(_FormatType_index)-1) {
		return "FormatType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FormatType_name[_FormatType_index[i]:_FormatType_index[i+1]]
}
